#development:
#  adapter: mysql2
#  encoding: utf8
#  database: my_store
#  pool: 5
#  username: root
#  password:
#
#test:
#  adapter: mysql2
#  encoding: utf8
#  database: my_store
#  pool: 5
#  username: root
#  password:
#
#production:
#  adapter: mysql2
#  encoding: utf8
#  database: my_store
#  pool: 5
#  username: root
#  password:


development:
  adapter: postgresql
  encoding: utf8
  database: my_store_development
  pool: 5
  username: postgres
  password: admin
test:
  adapter: postgresql
  encoding: utf8
  database: my_store_test
  pool: 5
  username: postgres
  password: admin

production:
  adapter: postgresql
  encoding: utf8
  database: my_store_production
  pool: 5
  username: postgres
  password: admin